=== Stratio/sparta/serving-core/src/main/resources/policy_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://sparkta.stratio.com",
  "type": "object",
  "properties": {
    "transformations": {
      "id": "http://sparkta.stratio.com/transformations",
      "type": "array",
      "items": {
        "id": "http://sparkta.stratio.com/transformations/",
        "type": "object",
        "properties": {
          "name": {
            "id": "http://sparkta.stratio.com/transformations/name",
            "type": "string"
          },
          "order": {
            "id": "http://sparkta.stratio.com/transformations/order",
            "type": "integer"
          },
          "inputField": {
            "id": "http://sparkta.stratio.com/transformations/inputField",
            "type": "string"
          },
          "outputFields": {
            "id": "http://sparkta.stratio.com/transformations/outputFields",
            "type": "array",
            "minItems": 1,
            "items": {
              "id": "http://sparkta.stratio.com/transformations/outputFields/",
              "type": "string"
            }
          },
          "type": {
            "id": "http://sparkta.stratio.com/transformations/type",
            "type": "string"
          },
          "configuration": {
            "id": "http://sparkta.stratio.com/transformations/configuration",
            "type": "object"
          }
        },
        "required": [
          "name",
          "order",
          "outputFields"
        ]
      }
    },
    "description": {
      "id": "http://sparkta.stratio.com/description",
      "type": "string"
    },
    "name": {
      "id": "http://sparkta.stratio.com/name",
      "type": "string"
    },
    "storageLevel": {
      "id": "http://sparkta.stratio.com/storageLevel",
      "type": "string"
    },
    "sparkStreamingWindow": {
      "id": "http://sparkta.stratio.com/sparkStreamingWindow",
      "type": "integer"
    },
    "checkpointPath": {
      "id": "http://sparkta.stratio.com/checkpointPath",
      "type": "string"
    },
    "rawData": {
      "id": "http://sparkta.stratio.com/rawData",
      "type": "object",
      "properties": {
        "enabled": {
          "id": "http://sparkta.stratio.com/rawData/enabled",
          "type": "string"
        },
        "path": {
          "id": "http://sparkta.stratio.com/rawData/path",
          "type": "string"
        }
      }
    },
    "input": {
      "id": "http://sparkta.stratio.com/input",
      "type": "object",
      "properties": {
        "name": {
          "id": "http://sparkta.stratio.com/input/name",
          "type": "string"
        },
        "type": {
          "id": "http://sparkta.stratio.com/input/type",
          "type": "string"
        },
        "configuration": {
          "id": "http://sparkta.stratio.com/input/configuration",
          "type": "object"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "cubes": {
      "id": "http://sparkta.stratio.com/cubes",
      "type": "array",
      "minItems": 1,
      "items": {
        "id": "http://sparkta.stratio.com/cubes/",
        "type": "object",
        "properties": {
          "name": {
            "id": "http://sparkta.stratio.com/cubes/name",
            "type": "string"
          },
          "checkpointConfig": {
            "id": "http://sparkta.stratio.com/cubes/checkpointConfig",
            "type": "object",
            "properties": {
              "timeDimension": {
                "id": "http://sparkta.stratio.com/cubes/checkpointConfig/timeDimension",
                "type": "string"
              },
              "granularity": {
                "id": "http://sparkta.stratio.com/cubes/checkpointConfig/granularity",
                "type": "string"
              },
              "interval": {
                "id": "http://sparkta.stratio.com/cubes/checkpointConfig/interval",
                "type": "integer"
              },
              "timeAvailability": {
                "id": "http://sparkta.stratio.com/cubes/checkpointConfig/timeAvailability",
                "type": "integer"
              }
            },
            "required": [
              "timeDimension",
              "granularity",
              "interval",
              "timeAvailability"
            ]
          },
          "dimensions": {
            "id": "http://sparkta.stratio.com/cubes/dimensions",
            "type": "array",
            "minItems": 1,
            "items": [
              {
                "id": "http://sparkta.stratio.com/cubes/dimensions/",
                "type": "object",
                "properties": {
                  "name": {
                    "id": "http://sparkta.stratio.com/cubes/dimensions/name",
                    "type": "string"
                  },
                  "field": {
                    "id": "http://sparkta.stratio.com/cubes/dimensions/field",
                    "type": "string"
                  },
                  "type": {
                    "id": "http://sparkta.stratio.com/cubes/dimensions/type",
                    "type": "string"
                  },
                  "precision": {
                    "id": "http://sparkta.stratio.com/cubes/dimensions/precision",
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "field"
                ]
              }
            ]
          },
          "operators": {
            "id": "http://sparkta.stratio.com/cubes/operators",
            "type": "array",
            "items": {
              "id": "http://sparkta.stratio.com/cubes/operators/",
              "type": "object",
              "properties": {
                "name": {
                  "id": "http://sparkta.stratio.com/cubes/operators/name",
                  "type": "string"
                },
                "type": {
                  "id": "http://sparkta.stratio.com/cubes/operators/type",
                  "type": "string"
                },
                "configuration": {
                  "id": "http://sparkta.stratio.com/cubes/operators/configuration",
                  "type": "object"
                }
              },
              "required": [
                "name",
                "type"
              ]
            }
          }
        },
        "required": [
          "name",
          "checkpointConfig",
          "dimensions"
        ]
      }
    },
    "outputs": {
      "id": "http://sparkta.stratio.com/outputs",
      "type": "array",
      "minItems": 1,
      "items": {
        "id": "http://sparkta.stratio.com/outputs/",
        "type": "object",
        "properties": {
          "name": {
            "id": "http://sparkta.stratio.com/outputs/name",
            "type": "string"
          },
          "type": {
            "id": "http://sparkta.stratio.com/outputs/type",
            "type": "string"
          },
          "configuration": {
            "id": "http://sparkta.stratio.com/outputs/configuration",
            "type": "object"
          }
        },
        "required": [
          "name",
          "type"
        ]
      }
    },
    "fragments": {
      "id": "http://sparkta.stratio.com/fragments",
      "type": "array",
      "items": {
        "id": "http://sparkta.stratio.com/fragments/",
        "type": "object",
        "properties": {
          "id": {
            "id": "http://sparkta.stratio.com/fragments/id",
            "type": "string"
          },
          "fragmentType": {
            "id": "http://sparkta.stratio.com/fragments/fragmentType",
            "type": "string"
          },
          "name": {
            "id": "http://sparkta.stratio.com/fragments/name",
            "type": "string"
          },
          "description": {
            "id": "http://sparkta.stratio.com/fragments/description",
            "type": "string"
          },
          "shortDescription": {
            "id": "http://sparkta.stratio.com/fragments/shortDescription",
            "type": "string"
          }
        },
        "required": [
          "id",
          "fragmentType",
          "name",
          "shortDescription",
          "description"
        ]
      }
    }
  },
  "required": [
    "name",
    "checkpointPath",
    "input",
    "cubes",
    "outputs"
  ]
}

=== Stratio/sparta/examples/policies/IRabbit-OPrint.json
{
  "name": "policy-rabbit",
  "description": "Input rabbit, output print",
  "sparkStreamingWindow": 2000,
  "rawData": {
    "enabled": "false",
    "path": "myTestParquetPath"
  },
  "checkpointPath": "checkpoint",
  "input":
  {
    "name": "in",
    "type": "RabbitMQ",
    "configuration": {
      "queue": "test",
      "host": "localhost",
      "port": "5672",
      "exchangeName": "twitterExchange",
      "routingKeys": [{"routingKey": "routingKey1"}]
    }
  }
,
  "transformations": [
    {
      "name": "morphline",
      "order": 0,
      "type": "Morphlines",
      "outputFields": [
        "appName",
        "timestamp",
        "geo",
        "tag",
        "twitterStatus"
      ],
      "configuration": {
        "morphline": {
          "id": "test1",
          "importCommands": [
            "org.kitesdk.**"
          ],
          "commands": [
            {
              "readJson": {}
            },
            {
              "extractJsonPaths": {
                "paths": {
                  "appName": "/appName",
                  "timestamp": "/timestamp",
                  "geo": "/geo",
                  "tag": "/tag",
                  "twitterStatus": "/twitterStatus"
                }
              }
            }
          ]
        }
      }
    },
    {
      "name": "timestamp",
      "order": 1,
      "type": "DateTime",
      "inputField": "timestamp",
      "outputFields": [
        "timestamp"
      ],
      "configuration": {
        "inputFormat": "unixMillis"
      }
    }
  ],
  "cubes": [
    {
      "name": "testCube",
      "checkpointConfig": {
        "timeDimension": "minute",
        "granularity": "minute",
        "interval": 30000,
        "timeAvailability": 60000
      },
      "dimensions": [
        {
          "field": "appName",
          "name": "appName"
        }
      ],
      "operators": [
        {
          "name": "countoperator",
          "type": "Count",
          "configuration": {}
        }
      ]
    }
  ],
  "outputs": [
    {
      "name": "out-print",
      "type": "Print",
      "configuration": {}
    }
  ]
}

=== Stratio/sparta/examples/policies/ITwitterJson-OCassandra.json
{
  "name": "policy-TwitterJson-Cassandra",
  "description": "policy-TwitterJson-Cassandra",
  "sparkStreamingWindow": 6000,
  "checkpointPath": "checkpoint",
  "rawData": {
    "enabled": "false",
    "path": "myTestParquetPath"
  },
  "input": {
    "name": "in-twitter-json",
    "type": "TwitterJson",
    "configuration": {
      "consumerKey": "*********",
      "consumerSecret": "*********",
      "accessToken": "*********",
      "accessTokenSecret": "*********"
    }
  },
  "transformations": [
    {
      "name": "morphline",
      "order": 0,
      "type": "Morphlines",
      "outputFields": [
        "text",
        "source",
        "hashtags",
        "retweets"
      ],
      "configuration": {
        "morphline": {
          "id": "test1",
          "importCommands": [
            "org.kitesdk.**"
          ],
          "commands": [
            {
              "readJson": {}
            },
            {
              "extractJsonPaths": {
                "paths": {
                  "text": "/text",
                  "source": "/source",
                  "hashtag": "/hashtagEntities[]/text",
                  "retweets": "/retweetCount"
                }
              }
            },
            {
              "removeFields": {
                "blacklist": [
                  "literal:_attachment_body"
                ]
              }
            }
          ]
        }
      }
    }
  ],
  "cubes": [
    {
      "name": "testCube",
      "checkpointConfig": {
        "timeDimension": "minute",
        "granularity": "minute",
        "interval": 30000,
        "timeAvailability": 60000
      },
      "dimensions": [
        {
          "field": "retweets",
          "name": "rtws"
        }
      ],
      "operators": [
        {
          "name": "total",
          "type": "Count",
          "configuration": {}
        }
      ]
    }
  ],
  "outputs": [
    {
      "name": "out-cassandra",
      "type": "Cassandra",
      "configuration": {
        "connectionHost": "127.0.0.1",
        "connectionPort": "9042",
        "cluster": "Test Cluster",
        "keyspace": "sparkta"
      }
    }
  ]
}

=== Stratio/sparta/test-at/src/test/resources/policies/ISocket-OCassandra-operators.json
{
  "name": "ATSocketCassandra",
  "description": "No description",
  "sparkStreamingWindow": 10000,
  "checkpointPath": "checkpoint",
  "rawData": {
    "enabled": "false",
    "path": ""
  },
  "input":
  {
    "name": "in-socket",
    "type": "Socket",
    "configuration": {
      "hostname": "localhost",
      "port": "10666"
    }
  }
,
  "transformations": [
    {
      "name": "morphline-parser",
      "order": 0,
      "type": "Morphlines",
      "outputFields": [
        "product",
        "price",
        "text"
      ],
      "configuration": {
        "morphline": {
          "id": "morphline1",
          "importCommands": [
            "org.kitesdk.**"
          ],
          "commands": [
            {
              "readCSV": {
                "separator": ",",
                "columns": [
                  "product",
                  "price",
                  "text"
                ],
                "trim": "true",
                "charset": "UTF-8",
                "quoteChar": "\"",
                "commentPrefix": "#"
              }
            }
          ]
        }
      }
    },
    {
      "name": "timestamp",
      "order": 1,
      "type": "DateTime",
      "outputFields": [
        "timestamp"
      ],
      "configuration": {
        "inputFormat": "autoGenerated"
      }
    }
  ],
  "cubes": [
    {
      "name": "testCubeWithTime",
      "checkpointConfig": {
        "timeDimension": "minute",
        "granularity": "minute",
        "interval": 100000,
        "timeAvailability": 90000
      },
      "dimensions": [
        {
          "name": "product",
          "field": "product"
        }
      ],
      "operators": [
        {
          "name": "avg_price",
          "type": "Avg",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "count_price",
          "type": "Count",
          "configuration": {}
        },
        {
          "name": "first_price",
          "type": "FirstValue",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "fulltext_price",
          "type": "FullText",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "last_price",
          "type": "LastValue",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "max_price",
          "type": "Max",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "median_price",
          "type": "Median",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "min_price",
          "type": "Min",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "range_price",
          "type": "Range",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "stddev_price",
          "type": "Stddev",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "sum_price",
          "type": "Sum",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "variance_price",
          "type": "Variance",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "entitycount_text",
          "type": "EntityCount",
          "configuration": {
            "inputField": "text",
            "split": " "
          }
        },
        {
          "name": "totalentity_text",
          "type": "TotalEntityCount",
          "configuration": {
            "inputField": "text",
            "split": " "
          }
        }
      ]
    },
    {
      "name": "testCubeWithoutTime",
      "checkpointConfig": {
        "timeDimension": "none",
        "granularity": "minute",
        "interval": 100000,
        "timeAvailability": 90000
      },
      "dimensions": [
        {
          "name": "product",
          "field": "product"
        }
      ],
      "operators": [
        {
          "name": "avg_price",
          "type": "Avg",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "count_price",
          "type": "Count",
          "configuration": {}
        },
        {
          "name": "first_price",
          "type": "FirstValue",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "fulltext_price",
          "type": "FullText",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "last_price",
          "type": "LastValue",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "max_price",
          "type": "Max",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "median_price",
          "type": "Median",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "min_price",
          "type": "Min",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "range_price",
          "type": "Range",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "stddev_price",
          "type": "Stddev",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "sum_price",
          "type": "Sum",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "variance_price",
          "type": "Variance",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "entitycount_text",
          "type": "EntityCount",
          "configuration": {
            "inputField": "text",
            "split": " "
          }
        },
        {
          "name": "totalentity_text",
          "type": "TotalEntityCount",
          "configuration": {
            "inputField": "text",
            "split": " "
          }
        }
      ]
    }
  ],
  "outputs": [
    {
      "name": "out-cassandra",
      "type": "Cassandra",
      "configuration": {
        "connectionHost": "127.0.0.1",
        "connectionPort": "9142",
        "cluster": "Test Cluster",
        "keyspace": "sparkta",
        "sparkProperties": [
          {
            "sparkPropertyKey": "spark.cassandra.connection.keep_alive_ms",
            "sparkPropertyValue": "180000"
          }
        ]
      }
    }
  ]
}

=== Stratio/sparta/examples/policies/IWebSocket-OMongo.json
{
  "name": "policy-websocket",
  "description": "Input kafka, output print",
  "sparkStreamingWindow": 2000,
  "checkpointPath": "checkpoint",
  "rawData": {
    "enabled": "false",
    "path": "myTestParquetPath"
  },
  "input":
  {
    "name": "in-websocket",
    "type": "WebSocket",
    "configuration": {
      "url": "ws://stream.meetup.com/2/rsvps"
    }
  },
  "transformations": [
    {
      "name": "morphline",
      "type": "Morphlines",
      "order": 0,
      "outputFields": [
        "response"
      ],
      "configuration": {
        "morphline": {
          "id": "morphline1",
          "importCommands": [
            "org.kitesdk.**"
          ],
          "commands": [
            {
              "readJson": {}
            },
            {
              "extractJsonPaths": {
                "paths": {
                  "response": "/response"
                }
              }
            },
            {
              "removeFields": {
                "blacklist": [
                  "literal:_attachment_body"
                ]
              }
            }
          ]
        }
      }
    }
  ],
  "cubes": [
    {
      "name": "testCube",
      "checkpointConfig": {
        "timeDimension": "minute",
        "granularity": "minute",
        "interval": 30000,
        "timeAvailability": 60000
      },
      "dimensions": [
        {
          "field": "response",
          "name": "response"
        }
      ],
      "operators": [
        {
          "name": "countoperator",
          "type": "Count",
          "configuration": {}
        }
      ]
    }
    ],
  "outputs": [
    {
      "name": "out-mongo",
      "type": "MongoDb",
      "configuration": {
        "hosts": [{"host": "localhost" , "port": "27017" }],
        "dbName": "sparkta"
      }
    }
  ]
}

=== Stratio/sparta/test-at/src/test/resources/policies/ISocket-OElasticsearch-operators.json
{

  "name": "ATSocketElasticsearch",
  "description": "No description",
  "sparkStreamingWindow": 10000,
  "checkpointPath": "checkpoint",
  "rawData": {
    "enabled": "false",
    "path": ""
  },
  "input":
    {
      "name": "in-socket",
      "type": "Socket",
      "configuration": {
        "hostname": "localhost",
        "port": "10666"
      }
    }
  ,
  "transformations": [
    {
      "name": "morphline-parser",
      "order": 0,
      "type": "Morphlines",
      "outputFields": [
        "product",
        "price",
        "text"
      ],
      "configuration": {
        "morphline": {
          "id": "morphline1",
          "importCommands": [
            "org.kitesdk.**"
          ],
          "commands": [
            {
              "readCSV": {
                "separator": ",",
                "columns": [
                  "product",
                  "price",
                  "text"
                ],
                "trim": "true",
                "charset": "UTF-8",
                "quoteChar": "\"",
                "commentPrefix": "#"
              }
            }
          ]
        }
      }
    },
    {
      "name": "timestamp",
      "order": 1,
      "type": "DateTime",
      "outputFields": [
        "timestamp"
      ],
      "configuration": {
        "inputFormat": "autoGenerated"
      }
    }
  ],
  "cubes": [
    {
      "name": "testCubeWithTime",
      "checkpointConfig": {
        "timeDimension": "minute",
        "granularity": "minute",
        "interval": 100000,
        "timeAvailability": 90000
      },
      "dimensions": [
        {
          "name": "product",
          "field": "product"
        }
      ],
      "operators": [
        {
          "name": "acc_price",
          "type": "Accumulator",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "avg_price",
          "type": "Avg",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "count_price",
          "type": "Count",
          "configuration": {}
        },
        {
          "name": "first_price",
          "type": "FirstValue",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "fulltext_price",
          "type": "FullText",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "mode_price",
          "type": "Mode",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "last_price",
          "type": "LastValue",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "max_price",
          "type": "Max",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "median_price",
          "type": "Median",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "min_price",
          "type": "Min",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "range_price",
          "type": "Range",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "stddev_price",
          "type": "Stddev",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "sum_price",
          "type": "Sum",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "variance_price",
          "type": "Variance",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "entityCount_text",
          "type": "EntityCount",
          "configuration": {
            "inputField": "text",
            "split": " "
          }
        },
        {
          "name": "totalEntity_text",
          "type": "TotalEntityCount",
          "configuration": {
            "inputField": "text",
            "split": " "
          }
        }
      ]
    },
    {
      "name": "testCubeWithoutTime",
      "checkpointConfig": {
        "timeDimension": "none",
        "granularity": "minute",
        "interval": 100000,
        "timeAvailability": 90000
      },
      "dimensions": [
        {
          "name": "product",
          "field": "product"
        }
      ],
      "operators": [
        {
          "name": "acc_price",
          "type": "Accumulator",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "avg_price",
          "type": "Avg",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "count_price",
          "type": "Count",
          "configuration": {}
        },
        {
          "name": "first_price",
          "type": "FirstValue",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "fulltext_price",
          "type": "FullText",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "mode_price",
          "type": "Mode",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "last_price",
          "type": "LastValue",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "max_price",
          "type": "Max",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "median_price",
          "type": "Median",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "min_price",
          "type": "Min",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "range_price",
          "type": "Range",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "stddev_price",
          "type": "Stddev",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "sum_price",
          "type": "Sum",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "variance_price",
          "type": "Variance",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "entityCount_text",
          "type": "EntityCount",
          "configuration": {
            "inputField": "text",
            "split": " "
          }
        },
        {
          "name": "totalEntity_text",
          "type": "TotalEntityCount",
          "configuration": {
            "inputField": "text",
            "split": " "
          }
        }
      ]
    }
  ],
  "outputs": [
    {
      "name": "out-elasticsearch",
      "type": "ElasticSearch",
      "configuration": {
        "nodes": [{"node":"localhost","tcpPort":"9300","httpPort":"9200"}],
        "isAutoCalculateId": "false",
        "clusterName": "sparkta-elasticsearch",
        "indexMapping": "day"
      }
    }
  ]
}
