=== Stratio/sparta/serving-core/src/main/resources/policy_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://sparkta.stratio.com",
  "type": "object",
  "properties": {
    "transformations": {
      "id": "http://sparkta.stratio.com/transformations",
      "type": "array",
      "items": {
        "id": "http://sparkta.stratio.com/transformations/",
        "type": "object",
        "properties": {
          "name": {
            "id": "http://sparkta.stratio.com/transformations/name",
            "type": "string"
          },
          "order": {
            "id": "http://sparkta.stratio.com/transformations/order",
            "type": "integer"
          },
          "inputField": {
            "id": "http://sparkta.stratio.com/transformations/inputField",
            "type": "string"
          },
          "outputFields": {
            "id": "http://sparkta.stratio.com/transformations/outputFields",
            "type": "array",
            "minItems": 1,
            "items": {
              "id": "http://sparkta.stratio.com/transformations/outputFields/",
              "type": "string"
            }
          },
          "type": {
            "id": "http://sparkta.stratio.com/transformations/type",
            "type": "string"
          },
          "configuration": {
            "id": "http://sparkta.stratio.com/transformations/configuration",
            "type": "object"
          }
        },
        "required": [
          "name",
          "order",
          "outputFields"
        ]
      }
    },
    "description": {
      "id": "http://sparkta.stratio.com/description",
      "type": "string"
    },
    "name": {
      "id": "http://sparkta.stratio.com/name",
      "type": "string"
    },
    "storageLevel": {
      "id": "http://sparkta.stratio.com/storageLevel",
      "type": "string"
    },
    "sparkStreamingWindow": {
      "id": "http://sparkta.stratio.com/sparkStreamingWindow",
      "type": "integer"
    },
    "checkpointPath": {
      "id": "http://sparkta.stratio.com/checkpointPath",
      "type": "string"
    },
    "rawData": {
      "id": "http://sparkta.stratio.com/rawData",
      "type": "object",
      "properties": {
        "enabled": {
          "id": "http://sparkta.stratio.com/rawData/enabled",
          "type": "string"
        },
        "path": {
          "id": "http://sparkta.stratio.com/rawData/path",
          "type": "string"
        }
      }
    },
    "input": {
      "id": "http://sparkta.stratio.com/input",
      "type": "object",
      "properties": {
        "name": {
          "id": "http://sparkta.stratio.com/input/name",
          "type": "string"
        },
        "type": {
          "id": "http://sparkta.stratio.com/input/type",
          "type": "string"
        },
        "configuration": {
          "id": "http://sparkta.stratio.com/input/configuration",
          "type": "object"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "cubes": {
      "id": "http://sparkta.stratio.com/cubes",
      "type": "array",
      "minItems": 1,
      "items": {
        "id": "http://sparkta.stratio.com/cubes/",
        "type": "object",
        "properties": {
          "name": {
            "id": "http://sparkta.stratio.com/cubes/name",
            "type": "string"
          },
          "checkpointConfig": {
            "id": "http://sparkta.stratio.com/cubes/checkpointConfig",
            "type": "object",
            "properties": {
              "timeDimension": {
                "id": "http://sparkta.stratio.com/cubes/checkpointConfig/timeDimension",
                "type": "string"
              },
              "granularity": {
                "id": "http://sparkta.stratio.com/cubes/checkpointConfig/granularity",
                "type": "string"
              },
              "interval": {
                "id": "http://sparkta.stratio.com/cubes/checkpointConfig/interval",
                "type": "integer"
              },
              "timeAvailability": {
                "id": "http://sparkta.stratio.com/cubes/checkpointConfig/timeAvailability",
                "type": "integer"
              }
            },
            "required": [
              "timeDimension",
              "granularity",
              "interval",
              "timeAvailability"
            ]
          },
          "dimensions": {
            "id": "http://sparkta.stratio.com/cubes/dimensions",
            "type": "array",
            "minItems": 1,
            "items": [
              {
                "id": "http://sparkta.stratio.com/cubes/dimensions/",
                "type": "object",
                "properties": {
                  "name": {
                    "id": "http://sparkta.stratio.com/cubes/dimensions/name",
                    "type": "string"
                  },
                  "field": {
                    "id": "http://sparkta.stratio.com/cubes/dimensions/field",
                    "type": "string"
                  },
                  "type": {
                    "id": "http://sparkta.stratio.com/cubes/dimensions/type",
                    "type": "string"
                  },
                  "precision": {
                    "id": "http://sparkta.stratio.com/cubes/dimensions/precision",
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "field"
                ]
              }
            ]
          },
          "operators": {
            "id": "http://sparkta.stratio.com/cubes/operators",
            "type": "array",
            "items": {
              "id": "http://sparkta.stratio.com/cubes/operators/",
              "type": "object",
              "properties": {
                "name": {
                  "id": "http://sparkta.stratio.com/cubes/operators/name",
                  "type": "string"
                },
                "type": {
                  "id": "http://sparkta.stratio.com/cubes/operators/type",
                  "type": "string"
                },
                "configuration": {
                  "id": "http://sparkta.stratio.com/cubes/operators/configuration",
                  "type": "object"
                }
              },
              "required": [
                "name",
                "type"
              ]
            }
          }
        },
        "required": [
          "name",
          "checkpointConfig",
          "dimensions"
        ]
      }
    },
    "outputs": {
      "id": "http://sparkta.stratio.com/outputs",
      "type": "array",
      "minItems": 1,
      "items": {
        "id": "http://sparkta.stratio.com/outputs/",
        "type": "object",
        "properties": {
          "name": {
            "id": "http://sparkta.stratio.com/outputs/name",
            "type": "string"
          },
          "type": {
            "id": "http://sparkta.stratio.com/outputs/type",
            "type": "string"
          },
          "configuration": {
            "id": "http://sparkta.stratio.com/outputs/configuration",
            "type": "object"
          }
        },
        "required": [
          "name",
          "type"
        ]
      }
    },
    "fragments": {
      "id": "http://sparkta.stratio.com/fragments",
      "type": "array",
      "items": {
        "id": "http://sparkta.stratio.com/fragments/",
        "type": "object",
        "properties": {
          "id": {
            "id": "http://sparkta.stratio.com/fragments/id",
            "type": "string"
          },
          "fragmentType": {
            "id": "http://sparkta.stratio.com/fragments/fragmentType",
            "type": "string"
          },
          "name": {
            "id": "http://sparkta.stratio.com/fragments/name",
            "type": "string"
          },
          "description": {
            "id": "http://sparkta.stratio.com/fragments/description",
            "type": "string"
          },
          "shortDescription": {
            "id": "http://sparkta.stratio.com/fragments/shortDescription",
            "type": "string"
          }
        },
        "required": [
          "id",
          "fragmentType",
          "name",
          "shortDescription",
          "description"
        ]
      }
    }
  },
  "required": [
    "name",
    "checkpointPath",
    "input",
    "cubes",
    "outputs"
  ]
}

=== Stratio/sparta/test-at/src/test/resources/policies/ISocket-OCsv-operators.json
{
  "name": "ATSocketCSV",
  "description": "No description",
  "sparkStreamingWindow": 2000,
  "checkpointPath": "checkpoint",
  "rawData": {
    "enabled": "false",
    "path": "myTestParquetPath"
  },
  "input":
    {
      "name": "in-socket",
      "type": "Socket",
      "configuration": {
        "hostname": "localhost",
        "port": "10666"
      }
    }
  ,
  "transformations": [
  {
    "name": "morphline-parser",
    "order": 0,
    "type": "Morphlines",
    "outputFields": [
      "product",
      "timestamp",
      "price",
      "text"
    ],
    "configuration": {
      "morphline": {
        "id": "morphline1",
        "importCommands": [
          "org.kitesdk.**"
        ],
        "commands": [
          {
            "readCSV": {
              "separator": ",",
              "columns": [
                "product",
                "price",
                "text"
              ],
              "trim": "true",
              "charset": "UTF-8",
              "quoteChar": "\"",
              "commentPrefix": "#"
            }
          }
        ]
      }
    }
  }
],
  "cubes": [
    {
      "name": "testCube",
      "checkpointConfig": {
        "timeDimension": "timestamp",
        "granularity": "day",
        "interval": 30000,
        "timeAvailability": 600000
      },
      "dimensions": [
        {
          "name": "product",
          "field": "product"
        }
      ],
      "operators": [
        {
          "name": "acc_price",
          "type": "Accumulator",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "avg_price",
          "type": "Avg",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "count_price",
          "type": "Count",
          "configuration": {}
        },
        {
          "name": "first_price",
          "type": "FirstValue",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "fulltext_price",
          "type": "FullText",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "last_price",
          "type": "LastValue",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "max_price",
          "type": "Max",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "median_price",
          "type": "Median",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "min_price",
          "type": "Min",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "mode_price",
          "type": "Mode",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "range_price",
          "type": "Range",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "stddev_price",
          "type": "Stddev",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "sum_price",
          "type": "Sum",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "variance_price",
          "type": "Variance",
          "configuration": {
            "inputField": "price"
          }
        },
        {
          "name": "entityCount_text",
          "type": "EntityCount",
          "configuration": {
            "inputField": "text",
            "split": " "
          }
        },
        {
          "name": "totalEntity_text",
          "type": "TotalEntityCount",
          "configuration": {
            "inputField": "text",
            "split": " "
          }
        }
      ]
    }
  ],
  "outputs": [
    {
      "name": "out-csv",
      "type": "Csv",
      "configuration": {
        "isAutoCalculateId": "false",
        "path": "/tmp/sparkta/operators/csv/",
        "header": "true",
        "delimiter": ","
      }
    }
  ]
}

=== Stratio/sparta/examples/policies/ITwitterJson-OCsv.json.json
{
  "name": "policy-TwitterJson-Csv",
  "description": "policy-TwitterJson-Csv",
  "sparkStreamingWindow": 6000,
  "checkpointPath": "checkpoint",
  "rawData": {
    "enabled": "false",
    "path": "myTestParquetPath"
  },
  "input": {
    "name": "in-twitter-json",
    "type": "TwitterJson",
    "configuration": {
      "consumerKey": "*********",
      "consumerSecret": "*********",
      "accessToken": "*********",
      "accessTokenSecret": "*********"
    }
  },
  "transformations": [
    {
      "name": "morphline",
      "order": 0,
      "type": "Morphlines",
      "outputFields": [
        "text",
        "source",
        "hashtags",
        "retweets"
      ],
      "configuration": {
        "morphline": {
          "id": "test1",
          "importCommands": [
            "org.kitesdk.**"
          ],
          "commands": [
            {
              "readJson": {}
            },
            {
              "extractJsonPaths": {
                "paths": {
                  "text": "/text",
                  "source": "/source",
                  "hashtag": "/hashtagEntities[]/text",
                  "retweets": "/retweetCount"
                }
              }
            },
            {
              "removeFields": {
                "blacklist": [
                  "literal:_attachment_body"
                ]
              }
            }
          ]
        }
      }
    }
  ],
  "cubes": [
    {
      "name": "testCube",
      "checkpointConfig": {
        "timeDimension": "minute",
        "granularity": "minute",
        "interval": 30000,
        "timeAvailability": 60000
      },
      "dimensions": [
        {
          "field": "retweets",
          "name": "retweets"
        }
      ],
      "operators": [
        {
          "name": "countoperator",
          "type": "Count",
          "configuration": {}
        }
      ]
    }
  ],
  "outputs": [
    {
      "name": "out-csv",
      "type": "Csv",
      "configuration": {
        "isAutoCalculateId": "false",
        "path": "/tmp/",
        "header": "false",
        "delimiter": ","
      }
    }
  ]
}

=== Stratio/sparta/examples/policies/IKafka-OCassandra-Detector.json
{
  "name": "KafkaToCassandra",
  "sparkStreamingWindow": 2000,
  "checkpointPath": "checkpoint",
  "rawData": {
    "enabled": "false",
    "partitionFormat": "day",
    "path": "myTestParquetPath"
  },
  "input":
  {
    "name": "in-kafka",
    "type": "Kafka",
    "configuration": {
      "topics": "det",
      "kafkaParams.zookeeper.connect": "localhost:2181",
      "kafkaParams.group.id": "testgroup",
      "storageLevel": "MEMORY_AND_DISK_SER_2"
    }
  }
,
  "transformations": [
    {
      "name": "detector-parser",
      "order": 1,
      "outputFields": [
        "recorded_at_ms",
        "company_root",
        "ou_vehicle",
        "geo",
        "alarm_code",
        "asset",
        "path_id",
        "rpm_event_avg",
        "odometer"
      ],
      "type": "Detector",
      "configuration": {}
    },
    {
      "name": "recorded_at_ms-parser",
      "inputField": "recorded_at_ms",
      "outputFields": [
        "recorded_at",
        "recorded_at2"
      ],
      "order": 2,
      "type": "DateTime",
      "configuration": {
        "inputFormat": "unixMillis"
      }
    }
  ],
  "cubes": [
    {
      "name": "rpmAvg",
      "checkpointConfig": {
        "timeDimension": "reco",
        "granularity": "minute",
        "interval": 30000,
        "timeAvailability": 60000000000000
      },
      "dimensions": [
        {
          "name": "companyRoot",
          "field": "company_root"
        },
        {
          "name": "ouVehicle",
          "field": "ou_vehicle"
        },
        {
          "name": "reco",
          "field": "recorded_at",
          "type": "DateTime",
          "precision": "minute"
        },
        {
          "name": "reco2",
          "field": "recorded_at2",
          "type": "DateTime",
          "precision": "minute",
          "configuration":{
            "typeOp":"datetime"
          }
        }
      ],
      "operators": [
        {
          "name": "avg_rpm",
          "type": "Avg",
          "configuration": {
            "inputField": "rpm_event_avg"
          }
        }
      ]
    }
  ],
  "outputs": [
    {
      "name": "out-cassandra",
      "type": "Cassandra",
      "configuration": {
        "connectionHost": "127.0.0.1",
        "connectionPort": "9042",
        "cluster": "Test Cluster",
        "keyspace": "sparkta"
      }
    }
  ]
}

=== Stratio/sparta/test-at/src/test/resources/policies/ISocket-OMongo-Detector.json
{
  "name": "ATSocketMongoDetector",
  "sparkStreamingWindow": 2000,
  "checkpointPath": "checkpoint",
  "rawData": {
    "enabled": "false",
    "partitionFormat": "day",
    "path": "myTestParquetPath"
  },
  "input":
    {
      "name": "in-socket",
      "type": "Socket",
      "configuration": {
        "hostname": "localhost",
        "port": "10666"
      }
    }
  ,
  "transformations": [
    {
      "name": "detector-parser",
      "order": 1,
      "outputFields": [
        "recorded_at_ms",
        "company_root",
        "ou_vehicle",
        "geo",
        "alarm_code",
        "asset",
        "path_id",
        "rpm_event_avg",
        "odometer"
      ],
      "type": "Detector",
      "configuration": {}
    },
    {
      "name": "recorded_at_ms-parser",
      "inputField": "recorded_at_ms",
      "outputFields": [
        "recorded_at_ms"
      ],
      "order": 2,
      "type": "DateTime",
      "configuration": {
        "inputFormat": "unixMillis"
      }
    }
  ],
  "cubes": [
    {
      "name": "rpmAvg",
      "checkpointConfig": {
        "timeDimension": "recordedAtMs",
        "granularity": "minute",
        "interval": 30000,
        "timeAvailability": 60000000000000
      },
      "dimensions": [
        {
          "name": "companyRoot",
          "field": "company_root"
        },
        {
          "name": "ouVehicle",
          "field": "ou_vehicle"
        },
        {
          "name": "geo",
          "field": "geo",
          "type": "GeoHash",
          "precision": "precision3"
        },
        {
          "name": "recordedAtMs",
          "field": "recorded_at_ms",
          "type": "DateTime",
          "precision": "minute"
        }
      ],
      "operators": [
        {
          "name": "avg_rpm",
          "type": "Avg",
          "configuration": {
            "inputField": "rpm_event_avg"
          }
        }
      ]
    },
    {
      "name": "maxMinOdometer",
      "checkpointConfig": {
        "timeDimension": "recordedAtMs",
        "granularity": "minute",
        "interval": 30000,
        "timeAvailability": 60000000000000
      },
      "dimensions": [
        {
          "name": "companyRoot",
          "field": "company_root"
        },
        {
          "name": "ouVehicle",
          "field": "ou_vehicle"
        },
        {
          "name": "asset",
          "field": "asset"
        },
        {
          "name": "recordedAtMs",
          "field": "recorded_at_ms",
          "type": "DateTime",
          "precision": "minute"
        },
        {
          "name": "pathId",
          "field": "path_id"
        }
      ],
      "operators": [
        {
          "name": "max-operator",
          "type": "Max",
          "configuration": {
            "inputField": "odometer"
          }
        },
        {
          "name": "min-operator",
          "type": "Min",
          "configuration": {
            "inputField": "odometer"
          }
        }
      ]
    }
  ],
  "outputs": [
    {
      "name": "out-mongo",
      "type": "MongoDb",
      "configuration": {
        "hosts": "localhost:60000",
        "dbName": "csvtest",
        "multiplexer": "false"
      }
    }
  ]
}

=== Stratio/sparta/examples/policies/Twitter-Stratio-Example.json
{
  "name": "twitter-stratio-example",
  "description": "twitter-stratio-example",
  "sparkStreamingWindow": 6000,
  "checkpointPath": "checkpoint",
  "rawData": {
    "enabled": "false",

    "path": "myTestParquetPath"
  },
  "input": {
    "name": "in-twitter-json",
    "type": "TwitterJson",
    "configuration": {
      "consumerKey": "****",
      "consumerSecret": "****",
      "accessToken": "****",
      "accessTokenSecret": "****",
      "termsOfSearch": "Stratio,#Stratio"
    }
  },
  "transformations": [
    {
      "name": "morphline",
      "order": 0,
      "type": "Morphlines",
      "outputFields": [
        "text"
      ],
      "configuration": {
        "morphline": {
          "id": "test1",
          "importCommands": [
            "org.kitesdk.**"
          ],
          "commands": [
            {
              "readJson": {}
            },
            {
              "extractJsonPaths": {
                "paths": {
                  "text": "/text"
               }
              }
            },
            {
              "removeFields": {
                "blacklist": [
                  "literal:_attachment_body"
                ]
              }
            }
          ]
        }
      }
    }
  ],
  "cubes": [
    {
      "name": "testCube",
      "checkpointConfig": {
        "timeDimension": "minute",
        "granularity": "minute",
        "interval": 30000,
        "timeAvailability": 60000
      },
      "dimensions": [
        {
          "field": "text",
          "name": "text"
        }
      ],
      "operators": [
        {
          "name": "total",
          "type": "Count",
          "configuration": {}
        }
      ]
    }
  ],
  "outputs": [
    {
      "name": "out-mongo",
      "type": "MongoDb",
      "configuration": {
        "hosts": [{"host": "localhost" , "port": "27017" }],
        "dbName": "sparkta"
      }
    }
  ]
}

=== Stratio/sparta/examples/policies/IKafka-OPrint.json
{
  "name": "policy-kafka",
  "description": "Input kafka, output print",
  "sparkStreamingWindow": 2000,
  "rawData": {
    "enabled": "false",
    "path": "myTestParquetPath"
  },
  "checkpointPath": "checkpoint",
  "input":
    {
      "name": "in-kafka",
      "type": "Kafka",
      "configuration": {
        "topics": [{"topic": "test", "partition" : "1"}],
        "zookeeper.connect": [{"host": "localhost", "port": "2181"}],
        "kafkaParams.group.id": "my-spt-grp"
      }
    }
  ,
  "transformations": [
    {
      "name": "morphline",
      "order": 0,
      "type": "Morphlines",
      "outputFields": [
        "appName",
        "timestamp",
        "geo",
        "tag",
        "twitterStatus"
      ],
      "configuration": {
        "morphline": {
          "id": "test1",
          "importCommands": [
            "org.kitesdk.**"
          ],
          "commands": [
            {
              "readJson": {}
            },
            {
              "extractJsonPaths": {
                "paths": {
                  "appName": "/appName",
                  "timestamp": "/timestamp",
                  "geo": "/geo",
                  "tag": "/tag",
                  "twitterStatus": "/twitterStatus"
                }
              }
            }
          ]
        }
      }
    }
  ],
  "cubes": [
    {
      "name": "testCube",
      "checkpointConfig": {
        "timeDimension": "minute",
        "granularity": "minute",
        "interval": 30000,
        "timeAvailability": 60000
      },
      "dimensions": [
        {
          "field": "appName",
          "name": "appName"
        }
      ],
      "operators": [
        {
          "name": "countoperator",
          "type": "Count",
          "configuration": {}
        }
      ]
    }
  ],
  "outputs": [
    {
      "name": "out-print",
      "type": "Print",
      "configuration": {}
    }
  ]
}
